// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace the values below with your actual Firebase project config.
/// To get these values:
/// 1. Go to https://console.firebase.google.com/
/// 2. Create a new project or select existing
/// 3. Add an Android app with package name: com.angaargrp.chai_tracker
/// 4. Download google-services.json and place in android/app/
/// 5. Run: flutterfire configure (optional, to auto-generate this file)
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpUy3vuaEXE7T7X974llA4DQQwE6JxV88',
    appId: '1:359692487908:android:ba274ad93b76ab867eb0f1',
    messagingSenderId: '359692487908',
    projectId: 'angaargrp',
    storageBucket: 'angaargrp.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase Android config

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyWSyil2ZdobGphwtH7akYF_q9Eidf0so',
    appId: '1:359692487908:ios:2ef10d46082a02647eb0f1',
    messagingSenderId: '359692487908',
    projectId: 'angaargrp',
    storageBucket: 'angaargrp.firebasestorage.app',
    iosBundleId: 'com.angaargrp.chaiTracker',
  );


  // TODO: Replace with your actual Firebase iOS config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpUy3vuaEXE7T7X974llA4DQQwE6JxV88',
    appId: '1:359692487908:web:ba274ad93b76ab867eb0f1',
    messagingSenderId: '359692487908',
    projectId: 'angaargrp',
    storageBucket: 'angaargrp.firebasestorage.app',
    authDomain: 'angaargrp.firebaseapp.com',
  );
}